### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by wermaxta** [Section9Labs/Cartero#40]
my os is Kali linux 
when i type 
root@kali:~/Cartero/bin# ./cartero 
i got this 
/root/Cartero/lib/cartero/base.rb:103:in `load': /root/Cartero/lib/cartero/commands/social/xmpp.rb:8: invalid multibyte char (US-ASCII) (SyntaxError)
/root/Cartero/lib/cartero/commands/social/xmpp.rb:8: invalid multibyte char (US-ASCII)
/root/Cartero/lib/cartero/commands/social/xmpp.rb:8: syntax error, unexpected $end, expecting ']'
          author: ["Matias P. Brutti <matias [©] section9labs.com>"],
                                                ^
	from /root/Cartero/lib/cartero/base.rb:103:in `block in load_commands'
	from /root/Cartero/lib/cartero/base.rb:102:in `each'
	from /root/Cartero/lib/cartero/base.rb:102:in `load_commands'
	from ./cartero:34:in `<main>'
root@kali:~/Cartero/bin# 
Thank you

**Comment by FreedomCoder** [comment]
Ups, sorry I thought I had fixed all of those in Kali.  Addint #encoding: utf-8  on the first line to the file (/root/Cartero/lib/cartero/commands/social/xmpp.rb)  should fix the problem. The issue arises because Kali does not handle UTF-8 by default on ruby files. and the author email as you can see has a special characters that breaks everything. :+1:  I already fixed this on the code and I am pushing a new change to fix the issue.

**Comment by FreedomCoder** [comment]
If you do a:
```shell
# bin/cartero Update --update
```
Should take you the latest and greatest version which already fixes this issue.
