### ISSUE TITLE
IV length too short

### ISSUE THREAD

**Issue by AbhishekShah212** [Section9Labs/Cartero#64]
Hi, 

Before I start with my issue, I'd just like to mention that you have done a great job with Cartero! It is a very well-written project and has really cool features like iMessage and XMPP!!!!

**********************
UPDATE:
I have found the source of the problem. It is the line about payloads. For instance, in carta.rb (under mailers within lib/commands), see line 203: 
     entity[:payload] = ::Cartero::CryptoBox.encrypt(entity.to_json)
************************
I am not extremely fluent in Ruby, but I think that there is no encrypt method within the CryptoBox Class in crypto_box.rb within the lib/cartero library; I think the encrypt function may be within the crypto directory (contains aes.rb and rbnacl.rb) . To temporarily fix the problem, I commented out that line, and I had mostly success. Still having troubles with mailing, but it probably is on my end. 

My problem is stated below:

I have been unable to send out mails with Mailer or text messages with Twilio because of a simple error that is known as "iv length too short". That's all I get. I don't know if they're are logs that describe the backtrace, but I have yet to find them. I have google searched the issue and I have found no luck. I think, however, the error may be in crypto_box.rb or the directory within lib that is called crypto (contains aes.rb and rbnacl.rb). 

Please let me know what suggestions you have.

Also, what is the purpose of the authentication and domain keys within the JSON email server files?
(They are usually set to plain and localhost.localdomain, respectively)

Thanks!
![error](https://cloud.githubusercontent.com/assets/16050306/16630837/ae661790-4381-11e6-89af-f6c8e44609f0.PNG)
![errorwithtwilio](https://cloud.githubusercontent.com/assets/16050306/16630838/ae6b1722-4381-11e6-8f79-67fc6caf6481.PNG)

**Comment by FreedomCoder** [comment]
So you should not escape that line. Since the UI is expecting the content of the payloads to be encrypted. I have run into this problem before and it was due to issues with my ~/.cartero/config file. 

How does it look like ? You should have something like this ?
less ~/.cartero/config
```json
  "editor" : "vim",
  "crypto" : "aes",
```
less ~/.cartero/.secret_material
and your secret should look something like
```json
{ "key" : "xxxxx=", "nonce" : "xxxxx=" }
```

I would delete the ~/.cartero/.secret_material and let cartero generate a new one. If you have not send any emails yet you should not have any issues. The CryptoBox is a class that gets dinamically populated upon configuration if you have crypt : aes it will load the crypto aes.rb otherwise it will default to the other one.

**Comment by FreedomCoder** [comment]
As far as the configuration details for the email json. Those are there because different emails require different values. If your server or local sendmail do not, there is no problem in removing them.  

If you use for example, a Google for Business domain with their servers as your sending platform. Lots of benefits from using that. It will require several of these fields

```json
{
    "name": "gmail_test",
    "type": "smtp",
    "options": {
        "address": "smtp.gmail.com",
        "port": "587",
        "enable_starttls_auto": true,
        "user_name": "Cartero",
        "password": "xxxaaaxxxx",
        "authentication": "plain",
        "domain": "business-test.com"
    }
}
```

**Comment by FreedomCoder** [comment]
Ohh, I forgot to mention the issue your IV might be too short as well, is because you configured the secret without AES and the IV will be too short. Also how small is your data entity?? could you try by adding info such as "Name" : "xxx" , "Last" : "yyyyy" to your .json . **Maybe that might be a bug on Cartero**.

**Comment by AbhishekShah212** [comment]
Wow, thanks for quick response!

I removed the ~/.cartero/.secret_material and my ~/.cartero/config did contain {"crypto": "aes"}.
After that, I re-ran the command and everything worked! My data entity was small when I encountered the error, but instead of using the small dataset, I just used the templates/dataset/sample.json and just changed the email addresses. 

Also, thanks for the info about the JSON Email Configuration. Really helped. Is there a one-stop shop or a listing of all the keys under options? How would I have known to use "enable_starttls_auto"?

Another thing: When a victim presses the link (which contains a key parameter) in an email, she or he gets redirected to a site . If that site is not running, does the click get recorded to the database? Based on my experience, I think so since there was nothing on the AdminWeb Console page, but I wanted to know why. 

Keep up the great work!

**Comment by FreedomCoder** [comment]
Ok many questions :-) 🚀 
**A)** Great news it worked.  👍 
**B)** I do not keep a list myself, but those are usually configuration values provided by the email provider. 
**C)**  In order for the click to be recorded something has to be listening. Otherwise, there is no way to make it work. I use the Cloner site to do it. and just point it to that.  Usually I never run a Phishing engagement without a Cloned site.  Although the site does not necessarily have to be hosting anything. It could technically be an empty site that just answers and collects the testing victims information.

**Comment by FreedomCoder** [comment]
BTW, thanks for using Cartero and remember we are always looking for contributors to expand the tool 🍔
